<?php

namespace nexxes\widgets\interfaces;

/**
 * Interface for widgets with identity.
 * 
 * Most widgets are anonymous widgets that have no need to be addressed directly after the page has been created.
 * Widgets that implement the iIdentifiable interface contain a page unique identifier so they can be accessed
 * and modified directly after the page has been rendered initially without rerendering the complete page.
 */
interface Identifiable extends Widget {
	/**
	 * Get the identifier of the widget.
	 * The identifier is unique for all widgets within a page.
	 * 
	 * @return string
	 */
	function getID();
	
	/**
	 * Set the identifier for the widget.
	 * Useful to avoid autogenerated identifiers for widgets that should hold the same id thru several instantiations of the same page.
	 * This allows parameters for that widgets to work when the page is restored from bookmarks, etc.
	 * 
	 * If the identifier is already used an exception is thrown.
	 * 
	 * @param string $newID
	 * @throws \InvalidArgumentException
	 */
	function setID($newID);
}
